### ISSUE TITLE
Disabling box shadow

### ISSUE THREAD

**Issue by PlashSpeed-Aiman** [AvaloniaCommunity/Notification.Avalonia#4]
How to disable shadow when notification is showed?

**Comment by GamerVII-NET** [comment]
I understand that it is no longer relevant, I think it will be useful

https://github.com/AvaloniaCommunity/Notification.Avalonia/blob/3a1e89af40969f44bc88149e73d9deb77d6ece5b/Notification.Avalonia/Themes/Generic.xaml#L296C33-L296C33

```
<Border BoxShadow="8 8 1 #99000000"
               x:Name="ItemsBorder"
               Margin="12,0,12,12"
               Padding="{TemplateBinding Padding}"
               Background="{TemplateBinding Background}"
               UseLayoutRounding="True">
                            <ItemsPresenter>
                            </ItemsPresenter>
</Border>
```

Remove this part

```
BoxShadow="8 8 1 #99000000"
```

**Comment by PlashSpeed-Aiman** [comment]
Thanks! I'm still very new to avalonia, this is extremely helpful

**Comment by GamerVII-NET** [comment]
Закрой тему, если у тебя больше нет вопросов )
