### ISSUE TITLE
Drop dependency on System.Reactive

### ISSUE THREAD

**Issue by giovani-luigi** [AvaloniaCommunity/Notification.Avalonia#6]
Can we drop dependency on System.Reactive?
From that namespace, you only use an extension method that adds overrides to IObservable.Subscribe() so we can subcribe with an anonymous delegate instead of an implementation of IObserver.

The extension method can be ignored if you wrap the action with AnonymousObserver from  Avalonia.Reactive namespace.

Example:

Before:

```
static NotificationMessageContainer()
        {
            ManagerProperty.Changed.Subscribe(x => ManagerPropertyChangedCallback(x.Sender, x));
        }
```

After:

```
static NotificationMessageContainer()
        {
            ManagerProperty.Changed.Subscribe(new AnonymousObserver<AvaloniaPropertyChangedEventArgs<NotificationMessageManager>>(
                x => ManagerPropertyChangedCallback(x.Sender, x)));
        }
```

I can open a PR if you want.

**Comment by CreateLab** [comment]
Better open pr
